### PR TITLE
censys search

### PR DESCRIPTION
**Pull request by CTIMarc**
Adds censys search on ipv4 dataset

### CODE REVIEW

**Comment by jeromeleonard** [comment]
Hello @CTIMarc, is there a difference with existing Censys analyzer ?

**Comment by CTIMarc** [comment]
Yes, it adds the possibilty to search anything on IPV4 dataset. The existing one doesn't permit to search multiple criterias.

**Comment by dadokkio** [comment]
Some thoughts:
- there are parameters in __init__ that are not available in json, so it'll take default everytime.
- the code is very similar to the existing one, probably is better to have just one python file for both and integrate your changes there

**Comment by dadokkio** [comment]
Closing since new pull with code merged instead of new analyzer.

**Pull request closed without merging**
