### PR TITLE
Fix for #410 removed wrapping of crt.sh result in a list

### PR DESCRIPTION
**Pull request by sprungknoedl**

### CODE REVIEW

**Comment by 3c7** [comment]
Thanks for your PR. I think there are some template changes necessary as the result value changes?

**Comment by sprungknoedl** [comment]
The current result templates are not working (this is how I detected this issue), as they expect only a 1-level deep list

So the current templates match the result value of this PR

**Comment by 3c7** [comment]
Oh snap.

**Comment by nadouani** [comment]
Approved by @3c7, merging the PR

**Pull request merged**
