### PR TITLE
Added Malpedia Analyzer

### PR DESCRIPTION
**Pull request by garanews**
This analyzer scans file againsts Yara Rules downloaded directly by Analyzer (every 10h) from Malpedia.
If a rule matches the analyzer try to retrieve more info from Malpedia portal such as the malware family (currently more than 600) and the actor group (tracked by Misp Galaxy Project).

image
image

### CODE REVIEW

**Comment by garanews** [comment]
Added Malpedia Analyzer

**Comment by 3c7** [comment]
Hey @garanews is it possible for you to base your commits on the develop branch? Would be great! :)

**Comment by garanews** [comment]
Sorry, created  #168 :)

**Comment by 3c7** [comment]
Thanks!

**Pull request closed without merging**
