### PR TITLE
GreyNoise analyzer

### PR DESCRIPTION
**Pull request by danielbrowne**
Creating a new analyzer for GreyNoise.
https://github.com/GreyNoise-Intelligence/api.greynoise.io

Referencing #231

### CODE REVIEW

**Comment by 3c7** [comment]
Hey @danielbrowne, thanks for your contribution! Do you have - by chance - already created a template for TheHive?

**Comment by danielbrowne** [comment]
Hi @3c7, I have not done that. I am not that familiar with the product, is that a requirement for this work to be useful?

**Comment by 3c7** [comment]
As the main use case for analyzers is the query out of TheHive, it would be cool if you could provide either a template for it or an example of the data returned by the analyzer so we can create a template. Examples for templates can be found in https://github.com/TheHive-Project/Cortex-Analyzers/tree/master/thehive-templates.

If no template is provided, the users will just see a JSON object which is not that UX friendly. ;)

**Comment by 3c7** [comment]
Ah, just saw that the returned data is quite nice described in the the link you provided. So, do you want to try to create a template or should we do it?

**Comment by danielbrowne** [comment]
@3c7 I am not sure that I will be able to get to it soon due to being flooded by other commitments, if it is easy for someone else to create it, that would be great :)

**Comment by 3c7** [comment]
Added a template. :)

**Comment by danielbrowne** [comment]
Thank you :)

**Pull request merged**
