### PR TITLE
Maltiverse Analyzer

### PR DESCRIPTION
**Pull request by ottimo**
I created all element to make a query to Maltiverse threat intelligence.
I added support to url domain ip and hash.

### CODE REVIEW

**Comment by 3c7** [comment]
I think the maltiverse python client cannot be used at the moment with python versions >= 3.4 due to https://github.com/maltiverse/python-maltiverse/pull/1 not merged.

**Comment by jeromeleonard** [comment]
hello, 

thank you for the PR and your contribution. While reviewing your PR I figured out that there is a composer file and a configuration file for TheHive that might not be part of the analyzer.

**Comment by ottimo** [comment]
> hello,
> 
> thank you for the PR and your contribution. While reviewing your PR I figured out that there is a composer file and a configuration file for TheHive that might not be part of the analyzer.

Ops, my mistake, I left them to help in development. Usually, I remove them when I do a release with git flow.

**Comment by ottimo** [comment]
> hello,
> 
> thank you for the PR and your contribution. While reviewing your PR I figured out that there is a composer file and a configuration file for TheHive that might not be part of the analyzer.

Do you prefer I will remove the wrong commits from pull request?

**Comment by 3c7** [comment]
Thanks @ottimo!

**Review by slumericanB — COMMENTED** [review]
good

**Pull request merged**
