### PR TITLE
Revert " DomainTools Iris - Risky DNS Responder"

### PR DESCRIPTION
**Pull request by jeromeleonard**
Reverts TheHive-Project/Cortex-Analyzers#587. It looks for specific short report in the observable to add a specific tag. Could you please describe the use-case or the need to do that ?

### CODE REVIEW

**Comment by ChuckWoodraska** [comment]
DomainTools customers would use this to easily tag a case and artifact based off the DomainTools Iris Risk Score data set.

**Comment by EngageCloud** [comment]
@nadouani similar to the first responder. 

Lmk. With these merged, we can launch the integration in March

**Comment by EngageCloud** [comment]
@nadouani a kind followup on this. Please lmk if anything is needed from our end.

**Comment by jeromeleonard** [comment]
code added for 2.6.0

**Pull request closed without merging**
