### PR TITLE
Adding some analyzers for common tools

### PR DESCRIPTION
**Pull request by alexgoedeke**
This pull requests has the following analyzers:
- Bluecoat: Check domains against Bluecoat's site reputation check
- MailParser: Parser *.msg files and check IPs. URLs and attachments against MISP, also run the FileInfo analyzer against every attachment
- ThreatCrowd: Run some basic checks against ThreatCrowd
- ipvoid: Search ipvoid for information.
- Th0r: Parse th0r reports and lookup outputs in MISP

### CODE REVIEW

**Comment by co-devs** [comment]
Any chance for review?  An IPvoid analyzer would be a nice addition.

**Comment by nadouani** [comment]
Hello, I'm personally not a fan of calling a Cortex service and a MISP from the analyzer code.

**Comment by nadouani** [comment]
And since the PR is old, it depends on a Cortex v1 which has no authentication mechanism etc..

**Comment by jeromeleonard** [comment]
I agree. for IPvoid there is the #455 that could be in a future release.

**Pull request closed without merging**
