### PR TITLE
Added AbuseIPDB analyzer

### PR DESCRIPTION
**Pull request by mlodic**
Related to issue #353

### CODE REVIEW

**Comment by saadkadhi** [comment]
Hi @mlodic. Thank you for your contribution. Can you please provide short and long report templates for this new analyzer?

**Comment by mlodic** [comment]
I'm writing them in a few days. I'll comment this issue once done.

**Comment by 3c7** [comment]
Already merged the analyzer files. Do you need help with the templates?

**Comment by mlodic** [comment]
Check this  #425 tell and tell me if they are ok. Thanks

**Comment by nadouani** [comment]
I took a look to the analyzer and I will make some changes to it:
- Improve the summary to display the taxonomy like `AbuseIPDB:Records=N`
- Add a new default value to the `days` config
- Set the `days` config type to `number` instead of `string`

**Comment by nadouani** [comment]
For security reasons, the API Key must also been passed as part of the POST body, not as query param (cf. https://www.abuseipdb.com/api)

**Pull request merged**
