### PR TITLE
Abuse_Finder : Add support to Python3.6

### PR DESCRIPTION
**Pull request by LetMeR00t**
This change is not enough (of course), it needs this PR to be merged :
https://github.com/certsocietegenerale/abuse_finder/pull/3

### CODE REVIEW

**Comment by LetMeR00t** [comment]
Hi guys,
My PR has been accepted.
This PR should be ready now :)

**Comment by nadouani** [comment]
Can you try to install the dependencies and make sure the analyzer works?

**Comment by LetMeR00t** [comment]
I will try this tomorrow.

**Comment by LetMeR00t** [comment]
Hi @nadouani ,
I've tested with this command after installing the requirements.txt using pip3:
`echo '{"data":"8.8.8.8","dataType":"ip"}' | python3 abusefinder.py`

I've no issue with the abuse_finder 0.2 package version

**Pull request merged**
