### PR TITLE
Added enhanced support for "Auto extraction" with observables for the emlparser analyzer

### PR DESCRIPTION
**Pull request by gekkeharry13**
To enhance the workflow of analists who analyse Scam E-mails, we wanted to make it possible to extract observables automatically out of the data generated by the emlparser (that is, header, body and such).
As we developed it specifically for this analyzer, I imported the class responsible for this feature and modified it as required.
I created the merge request as there are a few other teams that might benefit this enhancement.

The regexes seem to be pretty solid after a few weeks of testing (haven't heard any complaints from the team).

### CODE REVIEW

**Comment by gekkeharry13** [comment]
Probably should use a better regex for the IP address extraction. Something like this: (25[0-5]|2[0-4]\d|[1]\d\d|[1-9]\d|[1-9])(\.(25[0-5]|2[0-4]\d|[1]\d\d|[1-9]\d|\d)){3}

**Comment by 3c7** [comment]
You could also add `+` to the first part of the e-mail regex to properly parse e-mail addresses including filters.

**Comment by gekkeharry13** [comment]
@3c7 Can you give an example as there already is a + present so I am having some trouble understanding what you mean.

**Comment by gekkeharry13** [comment]
oohh, I did not knew this syntax (or mail filters in general) exist. I will add it and update my fork.

**Comment by 3c7** [comment]
In general those characters can be used in the local part of an e-mail address:
- uppercase and lowercase Latin letters A to Z and a to z
- digits 0 to 9
- printable characters others than letters and digit `!#$%&'*+-/=?^_`{|}~`

The `+` is not a filter in general, but is used as one in some mail servers. Using that quite often. :)

**Comment by gekkeharry13** [comment]
Thanks for the info @3c7!

**Comment by gekkeharry13** [comment]
Hi all, I am having some issues with my git stupidity. I have made these changes in master and now I have some other analyzers, responders that I am building, making, but I am kinda stuck here.

Do you guys like this proposal, because then I can tidy it for the merge or if you do not like it let me know. I think this needs to merge or be removed in order to place my next pull request (without it being dirty).

**Comment by nadouani** [comment]
Hi @gekkeharry13 I like the changes you added to the extractor, but I don't think it's a good idea to have a custom extractor within the analyzer.

What could be great it to try to add your changes in https://github.com/TheHive-Project/Cortex-Analyzers/blob/master/contrib/cortexutils/extractor.py which is part of `cortexutils` so that your options can be shared with the other analyzers.

That being said, I don't now does the `CustomExtractor` bring.

**Comment by gekkeharry13** [comment]
Ah yes, that would be great indeed, it should work as I literally copied that class.
The other thing is, in order to get more extracted observables I was thinking of creating some specific regexes that work on the mail header. This can enable us to extract hostnames without false positives where if the regex would be more generic it will generate false positives. That was the reason behind adding the class to the analyser.
For these regexes I can create a PR for cortexutils. I will let you know when it's done and then you can close this one.

**Comment by nadouani** [comment]
I think this is a good idea. 

@3c7 what do you think about that?

**Comment by 3c7** [comment]
Yeah, I like that, too.

**Comment by nadouani** [comment]
Instead of customizing the extractor with just a regex, I would customize it with a dataType + an extraction function. The function could be a regex test.

**Comment by gekkeharry13** [comment]
Yeah I agree. Something that extends the functionality of the automated extractor. I will change my repo and let you know when I think I have a good solution :)

**Comment by gekkeharry13** [comment]
Hi guys, so I have been working on the new approach today. The cortexutils fork can be found here:
[(https://github.com/gekkeharry13/cortexutils/tree/extractor-improvement/cortexutils)]

I am a bit stuck at how I can properly inherit the class (or make it a function) so that "def artifacts" isn't required in the analyzer itself. Maybe some of you are a bit more experienced and have a solution for this?

The latest changes I have added removed most of the code from the analyzer, back to the cortexutils.

**Comment by gekkeharry13** [comment]
Hereby the PR 👍 
https://github.com/TheHive-Project/cortexutils/pull/1

**Comment by ninSmith** [comment]
Poping in the conversation, someone's just asked me about attachment.    
Like an eml with attachment, would be nice to add the attachment as file observable to the case.

What do you guys think ?

**Comment by nadouani** [comment]
This is not possible for the moment, but it can be considered for the next version of cortex

**Comment by gekkeharry13** [comment]
Agree, the functionality can be extracted from synapse I guess? As we pop our mails through Synapse and files are extracted just fine When Cortex 3 is released :)

**Comment by ninSmith** [comment]
That's what I thought (and said).
Thanks for confirming.

**Comment by nadouani** [comment]
This is not handled in `cortexutils` dedicated repository

**Pull request closed without merging**
