### PR TITLE
New analyzer : Cyberprotect ThreatScore

### PR DESCRIPTION
**Pull request by remiallain**
View issue #373

### CODE REVIEW

**Comment by nadouani** [comment]
@remiallain any chance to provide some ioc samples to test the analyzer?

**Comment by remiallain** [comment]
Hello @nadouani , you can test it with this IP : 80.82.77.33
At this time, this service only provide a score/date. We are working on it to provide more information in a future version.

**Comment by nadouani** [comment]
This ip returns the following result:

```
{
  "summary": {
    "taxonomies": [
      {
        "predicate": "ThreatScore",
        "namespace": "Cyberprotect",
        "value": "not in database",
        "level": "info"
      }
    ]
  },
  "full": {
    "result": {
      "data": "80.82.77.33",
      "scores": [
        {
          "date": "2018-10-12",
          "score": "0.99"
        },
        {
          "date": "2018-10-11",
          "score": "0.558599982559681"
        }
      ]
    }
  },
  "success": true,
  "artifacts": [],
  "operations": []
}
```

The summary says `not in database` but we have a score, is this expected?

**Comment by nadouani** [comment]
Forget about it, I've made a change to the report structure but not to the summary function, my bad

**Pull request merged**
