### PR TITLE
feat: Adds SEKOIA analyzers

### PR DESCRIPTION
**Pull request by Darkheir**
This PR adds new analyzers to query the SEKOIA.IO Intelligence Center.

### CODE REVIEW

**Comment by Darkheir** [comment]
I just added the templates for the hive, let me know if other changes are necessary

**Comment by dadokkio** [comment]
Thanks for the submission. 
I was going to test it but I'm not able to understand how to generate the key.
Can you provide me some hints? I've created a free account and I tried to add keys to my community but it's not working.

**Comment by jeromeleonard** [comment]
Hi, 

we updated analyzers and responders to manage a better documentation to share useful information easily ( ex: https://thehive-project.github.io/Cortex-Analyzers/analyzers/DomainToolsIris/). So I encourage to update your pull request to add extra info. YOu can use the following guide: 
https://thehive-project.github.io/Cortex-Analyzers/analyzers_definition/

**Comment by Darkheir** [comment]
Hi, thank you for your feedback. I just updated the PR to add documentation.

**Pull request merged**
