### PR TITLE
[WIP] SinkDB: fix multiple issues

### PR DESCRIPTION
**Pull request by ilyaglow**
* Rename SinkDB 3rd level domain that IP is resolved against.
* Fix resulting IP that SinkDB returns for a sinkholed IP.
* Handle additional categories: scanner, phishing awareness.

### CODE REVIEW

**Comment by jeromeleonard** [comment]
Hello @ilyaglow, 

This PR is tagged [WIP]. Do you consider it ready to be merged ?

Thx.

**Comment by dadokkio** [comment]
Hi @jeromeleonard, this pull and #483 are both supporting v2 sinkdb api.
In my opinion #483 is done in a better way, so we can close this and keep the other one.
I've also updated #483 to support fqdn and url in pull #756.

**Comment by ilyaglow** [comment]
Hello, this PR doesn’t have a template changes for TheHive, but it works fine for me. At the time of submitting, I probably didn’t notice #483. However, this analyzer can run without API-key, compared to #483 and #756. 

@dadokkio maybe we can incorporate in #483 DNS lookups as a fallback in case an API key is not specified?

**Comment by dadokkio** [comment]
Yes, we could but I've some doubts (because I know dig just a little :P )
The API version works also for fqdn, domain and mail; this way will work just for ip?
In the code I see that also in your case the api key is attached to the query, in case of no api key it will lookup for ***.None.sinkdb-dnsapi.abuse.ch ?

**Comment by ilyaglow** [comment]
Whoops! You're right. It still needs the API key for DNS lookups. Sorry for being sloppy :)

So yeah, this PR can be closed.

**Comment by dadokkio** [comment]
No problem, thank you for the pull in any case :smile:

**Pull request closed without merging**
