### PR TITLE
Revert " DomainTools Iris - Malicious Tags Responder"

### PR DESCRIPTION
**Pull request by jeromeleonard**
Reverts TheHive-Project/Cortex-Analyzers#588. The responder is postponed. It looks for specific short report in the observable to add a specific tag. Could you please describe the use-case or the need to do that ?

### CODE REVIEW

**Comment by ChuckWoodraska** [comment]
DomainTools customers would use this to easily tag a case and artifact based off the DomainTools Iris Tags dataset.

**Comment by EngageCloud** [comment]
@nadouani tagging you to draw context to the Analyzers that we looked it. We added a couple of sample responders to allow customers to quick tag Cases based on malicious attributes in our dataset. Please lmk if you need additional context.

**Comment by EngageCloud** [comment]
@nadouani a kind followup on this. Please lmk if anything is needed from our end.

**Comment by jeromeleonard** [comment]
added to 2.6.0

**Pull request closed without merging**
