### PR TITLE
Edit Readme.MD for a goot view.

### PR DESCRIPTION
**Pull request by DanteDevil89**
At the end's Readme you not have same "\n".
sorry for my bad English.

##Basic configuration: The following settings are available for the script. 
QRadar: 
	proxies: << Use this for any proxy url's required 
		http: 
		https: 
	url: https://<ip/hostname>: << QRadar url 
	key: << QRadar API key. This can be the same as the key for the analyzer 
	verify: <True/False/pathtocert> << Defines whether or not certificate hostname validation 		is enabled. Provide a path to a CA file if you have a specific file with 				authorized CA's 
	enabled_datatypes: << Allows you to enable/disable certain datatypes. 
		- ip 
		- domain 
		- fqdn 
		- url
		- hash 
	search_limit : 1 << The amount of days it searches back in time 
	search_timeout : 86400 << The maximum duration it may take to complete the search
	polling_interval : 10 << polling interval for the search status 
	url_root_domain_field: << Field names 
		url_fqdn_field: 
		url_field: 
		mail_recipient_field: 
		mail_sender_field: 
		mail_send_qid: 
		mail_receive_qid: 
		hash_md5: 
		hash_sha1: 
		hash_sha256: 

TheHive: 
	proxies: << Use this for any proxy url's required 
		http: 
		https: 
	url: https://<ip/hostname> << The Hive url 
	key: << The Hive API key 
	verify: <True/False/pathtocert> << Defines whether or not certificate hostname validation 		is enabled. Provide a path to a CA file if you have a specific file with 		authorized CA's

### CODE REVIEW

**Comment by dadokkio** [comment]
Thanks @DanteDevil89 

If I'm not wrong this issue is related to:
Emlparser Analyzer - add ioc extraction 
IBMQRadar - new analyzer
Mailer Responder - add auth and support for case_task

I need to ask you to split this pull in 3 different part.
The ioc extraction has been started with the following commit and will be release soon https://github.com/TheHive-Project/Cortex-Analyzers/commit/99337a41eea6d10784a45c0c94e6aaebac4bbde7 and regarding mailer there is an ongoing discussion.

If you provide different pull will be easier and quicker for us to merge them.

**Comment by dadokkio** [comment]
I'm going to close this pull because it's very difficult to review and merge.
Please try to keep pull simple and follow the [pull request guideline ](https://github.com/TheHive-Project/CortexDocs/blob/master/api/how-to-create-an-analyzer.md#create-a-pull-request )

**Comment by DanteDevil89** [comment]
sorry @dadokkio, But i have suggesto also a change ok README.md. Because web view isn't good.

**Comment by garanews** [comment]
Hi @DanteDevil89 , what do you mean with issue for \n at the end of README.md ?
Can you show what is not good in your view?

**Comment by DanteDevil89** [comment]
Hi i view this!

READEME

**Comment by dadokkio** [comment]
@DanteDevil89 probably you want to make this change in @jeffrey-e  https://github.com/jeffrey-e/Cortex-Analyzers repo because the analyzer you are trying to fix in not yet available in this one.
Then if anyone wants to make separate pulls for IBMQRadar and Emlparser I'll be available to review them.

**Pull request closed without merging**
