### PR TITLE
Simple analyzer for GRR

### PR DESCRIPTION
**Pull request by pettai**
Simple analyzer for GRR that checks and map the GRR client_id of an IP / FQDN

### CODE REVIEW

**Comment by dadokkio** [comment]
I tried the analyzer and even if it's working it's not clear for me how it can be used.
I've installed grr and I've added some clients running random task on them.
Looking for a client fqdn it returns grr uuid, and just that. 
It's the only information you need? Because probably I'm missing something :smiley:

**Comment by pettai** [comment]
hi @dadokkio 
Yes, it's that simple, it return the UUID if the client is under GRR control. (That's typically what Analysers do, "do I know anything about this observable (IP or FQDN in this case)).

I'm working on a Responder for GRR, here is where the more useful things happens, like hunting for artifacts. But In order to run the Responder, you need to know if this client is under GRR-control and which UUID it has...

**Comment by dadokkio** [comment]
Ok, my idea was to add missing templates and I wanted to be sure I wasn't missing something.
The tool has a lot of functionality but you're right responder is a better place them.
So, I'm going to add templates to your pull so we'll be able to merge it.

**Comment by dadokkio** [comment]
I updated your pull with thehive templates and a notfound taxonomy https://github.com/TheHive-Project/Cortex-Analyzers/commit/f0737d0e6dd92c8a16203cf803c26fa5afe6012e

image

image

**Comment by pettai** [comment]
ok thx

**Pull request merged**
