### PR TITLE
Added file support for running analyzers locally

### PR DESCRIPTION
**Pull request by AlexBMJ**
This allows the "file" dict key to be used in job_definition for testing analyzing locally which take files as inputs.

### CODE REVIEW

**Comment by AlexBMJ** [comment]
Fixed spacing

**Comment by jeromeleonard** [comment]
Is there any interest to keep/update this program knowing that analyzers can be run manually like this ? 

  

### Requirements

```
$ tree
.
├── input
│   └── input.json
└── output
```

### Input (`input/input.json`)

```json
$ cat input/input.json 
{
    "data": "185.162.131.25",
    "tlp": 0,
    "parameters": {},
    "dataType": "ip",
    "config": {
        "jobTimeout": 30,
        "service": "",
        "url": "",
        "api_key": "",
        "proxy_http": "",
        "proxy": {
            "http": "",
            "https": ""
        },
        "max_tlp": 2,
        "max_pap": 2,
        "check_tlp": true,
        "check_pap": true,
        "proxy_https": "",
        "cacerts": "",
        "auto_extract_artifacts": false,        
        "jobCache": 10
    },
    "pap": 2,
    "message": "1"
```

### Running the program

```
python3 ~/Devel/TheHive-Project/Cortex-Analyzers/analyzers/DShield/DShield_lookup.py .
```
 or 

```
docker run --rm -v ${PWD}:/job cortexneurons/dshield_lookup:devel
```

### Output (`output/output.json`)

```json
$ cat output/output.json  | jq
{
  "success": true,
  "summary": {
    "taxonomies": [
      {
        "level": "safe",
        "namespace": "DShield",
        "predicate": "Score",
        "value": "0 count(s) / 0 attack(s) / 1 threatfeed(s)"
      }
    ]
  },
  "artifacts": [
    {
      "type": "autonomous-system",
      "value": "14576"
    },
    {
      "type": "mail",
      "value": "abuse@king-servers.com"
    }
  ],
  "full": {
    "ip": "185.162.131.25",
    "count": 0,
    "attacks": 0,
    "lastseen": "None",
    "firstseen": "None",
    "updated": "None",
    "comment": "None",
    "asabusecontact": "abuse@king-servers.com",
    "as": 14576,
    "asname": "HOSTING-SOLUTIONS",
    "ascountry": "US",
    "assize": 11264,
    "network": "185.162.131.0/24",
    "threatfeedscount": 1,
    "threatfeeds": {
      "ciarmy": {
        "lastseen": "2018-10-06",
        "firstseen": "2018-10-06"
      }
    },
    "maxrisk": 0,
    "reputation": "Safe"
  }
}
```

**Comment by AlexBMJ** [comment]
Didn't know it was possible to run scripts manually like this. Not sure if it is still useful then. My commit simply added file support to the pre-existing script: "utils/analyzer-runlocal.py". Maybe add the commands shown above to the documentation instead?

**Comment by AlexBMJ** [comment]
The original author of the script is @ndejong.

**Pull request closed without merging**
