### PR TITLE
New version of the Splunk analyzer for Cortex

### PR DESCRIPTION
**Pull request by LetMeR00t**
Hello everyone,

This is a new analyzer for Cortex which is able to search data into Splunk.
This version is different (even if inspired) from this PR : https://github.com/TheHive-Project/Cortex-Analyzers/pull/142

For those who known how Splunk work, I though that this PR was not a good version of how a Splunk analyzer must be. In this new version, we are using savedsearches. No request is hardcoded in the JSON files. Moreover, templates are now available for TheHive.

Please, let me know if I have to change something but this analyzer seems to be a must have for me.

I will update the CortexDocs soon to have all the details about this analyzer of course.

Thank you

### CODE REVIEW

**Comment by LetMeR00t** [comment]
Documentation is done and a PR is waiting.
Thank you

**Comment by LetMeR00t** [comment]
Hi,
upstream/master (your master) was merged into this feature
Thank you

**Comment by DaveCLowe** [comment]
What needs to happen to merge this PR? It would be very helpful.
Thanks

**Comment by LetMeR00t** [comment]
Hi,
upstream/master (your master) was merged into this feature
Thank you

**Comment by LetMeR00t** [comment]
Thank you.
If you need any help according to this analyzer, please mention me.

**Comment by jeromeleonard** [comment]
Yes we might indeed need some help. We used to use CortexDocs for documentation. In the meantime, we migrated our documentation to https://thehive-project.github.io/Cortex-Analyzers. Do you think it is possible to update this analyzer to contain all interesting info for the documentation ?  All instructions there:  https://thehive-project.github.io/Cortex-Analyzers/analyzers_definition/

**Comment by LetMeR00t** [comment]
@jeromeleonard ,
No problem at all, I will handle it.
Just one question, do you have a specific branch for this new documentation ? I can't find any example of the Markdown file used in your documentation on your repository ... of course to use the same structure.
Thank you :)

**Comment by jeromeleonard** [comment]
Everything is automatically generated based on JSON content and README.md file. An example can be found for The Domaintools_Iris analyzer.

**Comment by LetMeR00t** [comment]
Hi @jeromeleonard,
As requested, you will find the documentation in this new PR : https://github.com/TheHive-Project/Cortex-Analyzers/pull/837
I wasn't able to test it so if you have any trouble, please let me know.
Thank you

**Comment by jeromeleonard** [comment]
thank you very much. merged.

**Pull request merged**
