### PR TITLE
added check to validate that hash is in subject table

### PR DESCRIPTION
**Pull request by 0xmilkmix**
Solution for:
- https://github.com/TheHive-Project/Cortex-Analyzers/issues/805

### CODE REVIEW

**Comment by garanews** [comment]
Thanks, 8[.]8[.]8[.]8 now works, but for example this 172[.]93[.]184[.]62 no.

**Comment by garanews** [comment]
@0xmilkmix was you able to test with that ip?

**Review by jeromeleonard — APPROVED** [review]

**Comment by jeromeleonard** [comment]
@0xmilkmix  @garanews, to fix issue mentionned by @garanews  maybe an option is to remove `subjects = result.get(ip).get('subjects')` of L40 and update the code L33 to:

```
        if not result.get(ip, None):
            certificates = []
        else:
            certificates = list(result.get(ip).get('certificates'))
            subjects = result.get(ip).get('subjects', dict({}))
```

**Comment by 0xmilkmix** [comment]
> @0xmilkmix @garanews, to fix issue mentionned by @garanews maybe an option is to remove `subjects = result.get(ip).get('subjects')` of L40 and update the code L33 to:
> 
> ```
>         if not result.get(ip, None):
>             certificates = []
>         else:
>             certificates = list(result.get(ip).get('certificates'))
>             subjects = result.get(ip).get('subjects', dict({}))
> ```

Hello @jeromeleonard , indeed that will work.

I implemented the fix that you suggested. Sorry for the delay !

**Comment by jeromeleonard** [comment]
Thank you very much. We add it in the next release.

**Comment by jeromeleonard** [comment]
@0xmilkmix  for your information, I added some code to extract specific observables from the report and also added some useful info in tags and descriptions. If you think other interesting info should be extract, feel free to share.  

image

**Pull request merged**
