### PR TITLE
DomainTools Iris - Investigate Analyzer

### PR DESCRIPTION
**Pull request by ChuckWoodraska**
The current DomainTools Analyzers use an older set of APIs. This Analyzer uses the newer DomainTools Iris API for investigating a domain.

### CODE REVIEW

**Comment by ChuckWoodraska** [comment]
Added doc PR: https://github.com/TheHive-Project/CortexDocs/pull/54

**Comment by EngageCloud** [comment]
@nadouani can you kindly review and approve the above fix? Thanks, much

**Comment by EngageCloud** [comment]
@nadouani a kind followup on this. Please lmk if anything is needed from our end.

**Comment by jeromeleonard** [comment]
Hi @ChuckWoodraska. As we merge DomainToolsIris_Pivot first for last release, I have conflicts while merging this one. Could you please rebase it and check everything is fine in the .py and .html code ? 

Regards,

**Comment by ChuckWoodraska** [comment]
Rebasing onto the develop branch doesn't raise any merge conflicts for me. Am I supposed to be rebasing against a different branch other than develop?

**Comment by jeromeleonard** [comment]
thx. I think there was a pb on my side. This is working now. merging.

**Pull request merged**
