### PR TITLE
Analyzers for Valhalla and Thunderstorm

### PR DESCRIPTION
**Pull request by Neo23x0**
Two analyzers for our products 
- Valhalla (hash)
- Thunderstorm (file)

Valhalla is publicly accessible and can be queried with the demo key (default in configuration). 
THOR Thunderstorm is a commercial on-premise web service that receives samples and returns a scan result as JSON. Some customers asked for that analyzer. Should I provide analyzers for commercial services separately in our companies repo? (https://github.com/NextronSystems/Cortex-Analyzers)

I hope I did everything right. It's the first time I submit an analyzer. 
Both analyzers have been tested in a demo installation.

### CODE REVIEW

**Comment by dadokkio** [comment]
Can you improve analyzer json info following this guidelines https://thehive-project.github.io/Cortex-Analyzers/analyzers_definition/ with README, logo and subscription info? thanks!
Meanwhile I'm going to test them.

**Comment by dadokkio** [comment]
I was able to test valhalla, I had just to fix a little the template but it works fine :smile: 

image

**Comment by dadokkio** [comment]
For Thunderstom it's ok to have here in the pull. If you can provide me a temporary key I'll test it otherwise we will release it in any case without test.

**Comment by Neo23x0** [comment]
@dadokkio I cannot provide a key, but a source IP whitelisting 
Could you DM me on Twitter, Keybase or LinkeIn?

**Comment by dadokkio** [comment]
Ok, little fixes to template also here:
image

Now it's just missing info in the json, Readme and screenshots! Can you add them?

**Comment by Neo23x0** [comment]
So, what's missing is a README.md and a sub folder `./assets` with some screenshots of analyzed samples? Could you point me to a README someone else wrote? I can't see one in the folders of the `Cortex-Analyzers` repo. 
Is the content of the README something you include somewhere else? 

Screenshot 2021-02-23 at 15 07 17

**Comment by dadokkio** [comment]
If you switch to update_docs branch we are working to update documentation for all analyzer:
[here](https://github.com/TheHive-Project/Cortex-Analyzers/commits/feature/update_docs) some pulls with all modified analyzers

**Comment by Neo23x0** [comment]
Ah, I just noticed that the `DomainToolsIris` folder has that info even in the `master` branch.

**Comment by Neo23x0** [comment]
Do I need that favicon.svg as well?

**Comment by dadokkio** [comment]
I never noticed that.. so I hope not :smile:

**Comment by Neo23x0** [comment]
I've added the changes: 
- Updated JSON
- README.md
- Screenshots

**Pull request merged**
