### PR TITLE
Fixed some analyzers

### PR DESCRIPTION
**Pull request by emalderson**
- Fixed the JSON file of Maltiverse and Threatcrowd analyzers to remove unsupported observable types.
- Fixed URLhaus code, removing an if statement in which some non-existent fields of the JSON response are referenced in order to make the taxonomies building work

### CODE REVIEW

**Review by garanews — CHANGES_REQUESTED** [review]
URL in Maltiverse  is fully supported:
https://app.swaggerhub.com/apis-docs/maltiverse/api/1.0.0-oas3 
https://github.com/maltiverse/python-maltiverse#24---url

FQDN in Threatcrowd  is fully supported (example: https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=aoldaily.com and https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=share.aoldaily.com )


md5_hash  and sha256_hash are valid fields: https://urlhaus-api.abuse.ch/

**Comment by emalderson** [comment]
Thanks for your reply.
I know that those are supported on paper, but in fact using those types of observables with Maltiverse and Threatcrowd generates a lot of errors.
Furthermore, the taxonomies returned by URLHaus were always empty because those fields cannot be found in the json response. This has been found empirically analyzing the json response returned, not by reading the documentation.

**Comment by garanews** [comment]
Please report some example.

**Comment by emalderson** [comment]
Here are the outputs in Cortex after using Threatcrowd and Maltiverse with those types of observables:
https://i.imgur.com/I79KgvM.png
Here is the output in Cortex of URLHaus when something is found as malicious:
https://i.imgur.com/mZMOBfM.png

**Pull request closed without merging**
