### PR TITLE
DomainTools Iris - Pivot Analyzer

### PR DESCRIPTION
**Pull request by ChuckWoodraska**
This Analyzer uses the newer DomainTools Iris API for pivoting on IPs, Hashes, and email addresses.

### CODE REVIEW

**Comment by nadouani** [comment]
Hello @ChuckWoodraska Thanks a lot for this PR, is it possible to add a PR to https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md to include this analyzer?

**Comment by ChuckWoodraska** [comment]
Added doc PR: https://github.com/TheHive-Project/CortexDocs/pull/54

**Comment by ChuckWoodraska** [comment]
Added doc PR: https://github.com/TheHive-Project/CortexDocs/pull/54

**Comment by nadouani** [comment]
Hello @ChuckWoodraska is it possible to have a sample screenshot of analyzer report and mini reports? (blogging purpose) :)

**Comment by ChuckWoodraska** [comment]
@nadouani I added screenshots to the PR for the short and long summaries.

**Comment by nadouani** [comment]
@ChuckWoodraska I just wanted to know if there is any particular reason to create a `DomainToolsIris` folder instead of using the existing `DomainTools` folder?

**Comment by EngageCloud** [comment]
> @ChuckWoodraska I just wanted to know if there is any particular reason to create a `DomainToolsIris` folder instead of using the existing `DomainTools` folder?

Hi Nabil @nadouani, this is Sourin the associate PM and thought I will make an attempt to explain this. DomainTools Iris is the latest product offering and does not overlap with the older Classic toolsets. The APIs associated hence have different capabilities, with Iris having an extended dataset. 

As a product strategy, we are no longer extending the older Integration (API capabilities). So if there are customers who continue to exist the original DomainTools Hive Cortex users, they can.  However, I beleive it was a community contribution so we cannot support the codeset. With Iris, users (our customers) can reach out to us for extended support etc.

Does this make sense?

**Comment by nadouani** [comment]
Hello @EngageCloud Ok, this makes sense. We need to communicate correctly about it. Could you please DM me to talk about this topic?

**Comment by EngageCloud** [comment]
> Hello @EngageCloud Ok, this makes sense. We need to communicate correctly about it. Could you please DM me to talk about this topic?

@nadouani don't know a way to DM you in GH (anymore). Since I don't see your email on the profile, I decided its best not to pry in git-log :). Can you send me an email spaul@domaintools.com

**Comment by EngageCloud** [comment]
> > Hello @EngageCloud Ok, this makes sense. We need to communicate correctly about it. Could you please DM me to talk about this topic?
> 
> @nadouani don't know a way to DM you in GH (anymore). Since I don't see your email on the profile, I decided its best not to pry in git-log :). Can you send me an email [spaul@domaintools.com](mailto:spaul@domaintools.com)

Hi, @nadouani just following up on this thread to see if there are any further actions needed from our end. If so, look forward to your note (my email above).

**Comment by jeromeleonard** [comment]
@EngageCloud I will review this analyzer, sending you an email.

**Pull request merged**
