### PR TITLE
WIP/evaluation: Using optionally Docker to prevent compatibility problems with Analyzers

### PR DESCRIPTION
**Pull request by 3c7**
This is WIP and needs discussion.

### CODE REVIEW

**Comment by BrevilleBro** [comment]
Good work @3c7 , I think this is the way forward for Cortex analyzers if we want to maintain compatibility.

**Comment by ryanmcvicar** [comment]
Would this allow cortex analyzers to start running on different Docker images (Windows)? For example I could see a cortex analyzer that check Office 365 block lists which are only available over PowerShell at the moment.

**Comment by geekscrapy** [comment]
@ryan I guess if you used docker swarm that'd be fairly easy to distribute analyzers across platforms

**Comment by 3c7** [comment]
- [ ] Fix cortex-base-python3 image
- [ ] Fix `unterminated quoted string` bug
- [ ] Check for possibilities to reduce image sizes

**Comment by 3c7** [comment]
Basically finished, just postponed to the next cortex (bugfix) release.

**Comment by 3c7** [comment]
Continued in #334 as I cannot change the branch.

**Pull request closed without merging**
