### PR TITLE
Analyzer for DNS Lookingglass

### PR DESCRIPTION
**Pull request by LaZyDK**
Simple analyzer to use DNS Lookingglass API from ISC SANS.
https://www.dshield.org/tools/dnslookup.html

### CODE REVIEW

**Comment by dadokkio** [comment]
Hi, can you complete analyzer definition following https://thehive-project.github.io/Cortex-Analyzers/analyzers_definition/ ? Thanks :smiley:

**Comment by LaZyDK** [comment]
Can you point out what is missing? :)

**Comment by dadokkio** [comment]
Info about registration/subscription, logo and if possible screens for report.

**Comment by LaZyDK** [comment]
> Info about registration/subscription, logo and if possible screens for report.

Screenshots are now in the assets folder. 
Readme file is also in place.

**Comment by dadokkio** [comment]
I made minor fixes to json and template. Thanks :smiley:

**Pull request merged**
