### PR TITLE
Added VULNS taxonomies from Shodan and flag suspicious tag

### PR DESCRIPTION
**Pull request by CERT-ARKEA**
Add vulns (CVE) list from host, tag shodan: CVE:xxxx whith suspicious level color

### CODE REVIEW

**Comment by dadokkio** [comment]
Hi, tried with random samples on shodan but some of them have too much vulns in them

image

Probably is better to show them only if there are few vulns and count them in the other case.

**Comment by CERT-ARKEA** [comment]
Hi,
add modification, now count CVE result and return only CVE names if result < 3, else return count number.

**Comment by dadokkio** [comment]
OT. you think it'll be useful to add those info also in the long template?

**Comment by CERT-ARKEA** [comment]
hum, for me, the CVE numbers that affect the observable is important. This numbers is in the shodan json return by cortex. I'm not convinced that the count of CVE is useful in this template (you speak well about de json return of Shodan host analyser ?) but it's my own opinion :) Perhaps other users need this information to determinate the criticity of observable

**Comment by dadokkio** [comment]
the question was because with your fix I can see the cve info in taxonomies but when I open the observable to check the long template that info is not present. Probably we could add a cve panel with the list of cve and links to their definitions

**Comment by CERT-ARKEA** [comment]
oh yes that's a great idea, the CVE panel will be extremely interessant

**Comment by dadokkio** [comment]
This is a first attempt:
image

**Comment by CERT-ARKEA** [comment]
Nice job ! Very useful indeed :)

**Comment by dadokkio** [comment]
I tried to add to templates to your pull and I ended up with a new one #776

**Comment by nadouani** [comment]
This PR has been merged manually. Thanks @CERT-ARKEA

**Pull request closed without merging**
