### PR TITLE
New analyser: File Strings

### PR DESCRIPTION
**Pull request by j-i-m-b-o**
A simple analyser to find printable strings within files. 

I've personally found this analyser to be a useful first step when dealing with various types of unknown file so wanted to make it available to others.

### CODE REVIEW

**Comment by geekscrapy** [comment]
It may also be good to take a look at this at the same time:
https://github.com/fireeye/flare-floss

**Comment by jeromeleonard** [comment]
I propose to add this feature as a submodule in FileInfo.

**Comment by dadokkio** [comment]
I've added the feature as submodule. I just need to finish templates.
For flare-floss the support must wait because it doesn't support python3 yet

**Comment by geekscrapy** [comment]
Can always use the floss binary?

**Comment by geekscrapy** [comment]
So, if you use this version it's not floss per-say, but it's more capable than basic strings, and it can rank  the strings in order of maliciousness with rankstrings

https://github.com/fireeye/stringsifter

**Comment by geekscrapy** [comment]
Also, could always use the binary version of floss?

**Comment by dadokkio** [comment]
Ok, I'll try with the binary tomorrow.
In any case template for strings looks very strange and way too long.

This is a preview:
image

**Comment by 3c7** [comment]
I've already added FLOSS as a submodule for FileInfo: https://github.com/TheHive-Project/Cortex-Analyzers/tree/feature/fileinfo_floss

**Comment by 3c7** [comment]
(That's why I was assigned ;) )

**Comment by dadokkio** [comment]
sorry, I didn't knew that and it seems way better than my first attempt with floss :)

**Comment by geekscrapy** [comment]
I'd say, if you want to at least have the most useful stuff at the top of the long list, use `rankstrings.py` on the generated output from `strings`.

**Comment by dadokkio** [comment]
@3c7  will you propose a pull request with your changes?

**Comment by 3c7** [comment]
Need more time to fix the template. Currently no time to work on Analyzer stuff.

**Comment by dadokkio** [comment]
no problem. The plan is to release milestone 2.6.0 this friday, if you need more time I'll move your pr to next release :+1:

**Comment by dadokkio** [comment]
I've added a fix for the template in your repo. 
Probably this should resolve the issue (related to duplicated items in the ng-repeat loop)

image

**Pull request closed without merging**
