### PR TITLE
HarfangLab EDR responder contribution

### PR DESCRIPTION
**Pull request by Pierre-HarfangLab**
Hello,

This PR contains the HarfangLab EDR responder with 31 different flavors. 
It is related to issue #1125.

Thanks,
Pierre

### CODE REVIEW

**Comment by jeromeleonard** [comment]
Hello, 

I think this could be nice to have the logo and know if a subscription is required or not to run these responders. like for: https://thehive-project.github.io/Cortex-Analyzers/analyzers/DomainToolsIris/

Documentation: https://thehive-project.github.io/Cortex-Analyzers/dev_guides/analyzers_definition/

**Comment by Pierre-HarfangLab** [comment]
Hi Jerome,

I added the logo and subscription information, knowing that HarfangLab is not strictly an online service (like DomainTools) but an EDR provider with SaaS on on-premises deployments.

Regards,
Pierre



________________________________

**Comment by Pierre-HarfangLab** [comment]
Hi Jerome,

There is a complete README associated to HarfangLab's responders in the MR. 
What kind of additional docs do you need ?

**Comment by nadouani** [comment]
Hello @Pierre-HarfangLab 

The readme file is perfect. We will include this integration in the next release.

**Review by jeromeleonard — APPROVED** [review]

**Pull request merged**
