### PR TITLE
add Emailrep analyzer

### PR DESCRIPTION
**Pull request by ninoseki**
Implement #466

### CODE REVIEW

**Comment by 3c7** [comment]
Thanks, @ninoseki!

**Comment by ninoseki** [comment]
@3c7 The API reponse schema of Emailrep has been changed and current implementation does'nt work well.
Should I make a PR to `release/2.4.0` to fix the issue?

**Comment by 3c7** [comment]
Hey @ninoseki, that would be great!

**Comment by 3c7** [comment]
I'm reverting the merge for now and you should be able to push the changes directly via this PR.

**Pull request merged**
