### PR TITLE
New Responder KnowBe4

### PR DESCRIPTION
**Pull request by arnydo**
Addresses #548

### CODE REVIEW

**Comment by arnydo** [comment]
Sample event
image

**Comment by nadouani** [comment]
Hello @arnydo Thanks for the PR.

**Comment by nadouani** [comment]
@arnydo Is it possible to cook an update for https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md? Thanks

**Comment by arnydo** [comment]
Of course. Added PR here https://github.com/TheHive-Project/CortexDocs/pull/53

**Comment by nadouani** [comment]
I've renamed `hive_url` to `thehive_url` :)

**Comment by nadouani** [comment]
It looks like the `KnowBe4` folder is duplicate in `analyzers` and `responders` folder, is this expected? I don't think so :)

**Comment by arnydo** [comment]
Woops. No, it should have only been in responders...

**Pull request merged**
