### PR TITLE
new LastInfoSec analyzers for hash and domain

### PR DESCRIPTION
**Pull request by remydewa**
new LastInfoSec analyzers for hash and domain
Related issue: #753

### CODE REVIEW

**Comment by remydewa** [comment]
LastInfoSec analyzer added. Ready to merge

**Comment by remydewa** [comment]
Do I have something to do? Who will validate the PR? What is the process of validation?

Thanks :)

**Comment by dadokkio** [comment]
Hi, thanks for the pull. 
One of the missing step to be integrated are the templates for the hive. Can you add create and add them to the pull?
Then someone of the reviewer will test your code, review it, and then it'll merged (probably in 2.8.0)

**Comment by remydewa** [comment]
@dadokkio Hi, thanks for reply. 
I have added the templates. Don't hesitate to come back to me if needed.

Rémy

**Comment by dadokkio** [comment]
Perfect, do you think I could ask for a temporary key just to test the code?

**Comment by remydewa** [comment]
Yes, for sure. How can we exchange about that to avoid writing it on this post? Do you have an email address to send the contract details? 

thanks,

Rémy

**Comment by dadokkio** [comment]
Hi @remydewa , I didn't receive any email yet. It this correct?

**Pull request merged**
