### PR TITLE
New analyzer: Tenable SecurityCenter

### PR DESCRIPTION
**Pull request by InsanesTheName**
This analyzer launches a scan via SecurityCenter on an IP/FQDN using the new SecurityCenter API.

### CODE REVIEW

**Comment by k41zen** [comment]
I wonder if you can help me please? When I configure this and run it through Cortex I get an error saying "Invalid Output". When I try and run this from the command line I get "Error 'token'. Is this something you have got working yourself? Could you help me configure and troubleshoot please?

**Comment by k41zen** [comment]
Finally had some time to review this. The repo was hard coded as number 1. Our's wasn't number 1 so modified the .json and .py to ask for the repo number in the requirements.

**Comment by InsanesTheName** [comment]
Good catch - thanks. And sorry for my lack of response; I'm no longer with the company I built this for, and it kind of fell off my radar since then.

Can you submit those changes as a pull request to my fork? Unfortunately I no longer have an environment to test with, but I'd be happy to get them in here for someone on the project to review.

**Comment by jeromeleonard** [comment]
Hi, 

thank you for your PR. In order to release it, could you please provide report templates for TheHive ? 
Thx.

**Comment by jeromeleonard** [comment]
Hi @InsanesTheName, 

I made a mistake by basing you PR on a temporary branch for a release. Now I cannot reopen it. Could you please submit it again ? Could you please add report templates for TheHive or do you need help to do that ?

**Comment by LaZyDK** [comment]
With a few chances could this one work for Tenable.io as well?

**Comment by InsanesTheName** [comment]
See #758 for resubmission.

**Pull request closed without merging**
